### ISSUE TITLE
Auto detect Location of the user 

### ISSUE THREAD

**Issue by vagabon-09** [vagabon-09/Smart-Weather#2]
This feature is working fine only on my own device which I use for development. When I sharing this with my buddies the auto detect location is not working. Till now I shared it with two people but it is not working on their device but it's working on my device.

**Comment by garvit123-oss** [comment]
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE">
    </uses-permission>
Use this in manifest file

**Comment by vagabon-09** [comment]
Still, it's not working
